### ISSUE TITLE
declination sign incorrect in output

### ISSUE THREAD

**Issue by adamdeller** [walterfb/pmpar#1]
I think I found a bug in pmpar where the output has the wrong sign for declination for declinations in the range -1 < d < 0 degrees.  Try the below as input, you'll get +ve declination (00:32:41.xxx) in the printed output:
epoch = 56000.0

#55610.5627 16:07:12.06197320 2.306e-06 -00:32:41.5002080 7.679e-05
55976.5287 16:07:12.06017190 1.407e-06 -00:32:41.5281870 4.912e-05
55988.5167 16:07:12.06011370 1.044e-06 -00:32:41.5292610 3.721e-05
56163.0181 16:07:12.05914930 3.728e-06 -00:32:41.5408900 0.00013779
56170.9962 16:07:12.05911860 1.46e-06 -00:32:41.5417760 4.908e-05
56342.5266 16:07:12.05841260 2.004e-06 -00:32:41.5557980 6.352e-05
56371.4786 16:07:12.05825560 1.508e-06 -00:32:41.5580010 5.257e-05
56527.0215 16:07:12.05738900 2.678e-06 -00:32:41.5691550 8.642e-05

**Comment by walterfb** [comment]
Oh dear...  This again...  Shami reported the equivalent problem on the
_input_ side years ago.  I think that was fixed.  If you haven't tried
yourself to fix yet I'll put it on my urgent list...

-W

**Comment by walterfb** [comment]
Fixed.  was on the reading side, not writing side.
